import { useEffect, useMemo, useState } from 'react'
import { Download, Filter, Search, Waypoints } from 'lucide-react'
import { buildOperationalRegister, operationalRegisterCsv, type OperationalEventCategory, type OperationalSources } from './operational'
import { useLanguage } from './i18n'
import { formatRelativeTime, formatZonedDateTime } from './time'
export function OperationalRegisterPage(props: OperationalSources & { timeZone?: string }) {
 const { language, locale } = useLanguage(); const timeZone=props.timeZone||'Europe/Madrid'; const [now,setNow]=useState(()=>new Date()); useEffect(()=>{const timer=window.setInterval(()=>setNow(new Date()),60000);return()=>window.clearInterval(timer)},[]); const [query,setQuery]=useState(''); const [category,setCategory]=useState<'all'|OperationalEventCategory>('all'); const [date,setDate]=useState('')
 const events=useMemo(()=>buildOperationalRegister(props),[props]); const filtered=events.filter(e=>(category==='all'||e.category===category)&&(!date||e.performedAt.slice(0,10)===date)&&(!query||`${e.title} ${e.operator} ${e.reference} ${e.wineLotId} ${e.productLotId}`.toLowerCase().includes(query.toLowerCase())))
 const exportCsv=()=>{const blob=new Blob(['\ufeff'+operationalRegisterCsv(filtered)],{type:'text/csv;charset=utf-8'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url;a.download=`registro-operativo-${date||'completo'}.csv`;a.click();URL.revokeObjectURL(url)}
 const labels=language==='es'?{k:'Control operativo',title:'Registro operativo',desc:'Cronología unificada de recepción, elaboración, movimientos, insumos, crianza y embotellado.',search:'Buscar lote, operador o referencia',all:'Todos',export:'Exportar CSV',empty:'No hay operaciones con estos filtros'}:{k:'Operational control',title:'Operational register',desc:'Unified chronology for intake, production, movements, supplies, ageing and bottling.',search:'Search lot, operator or reference',all:'All',export:'Export CSV',empty:'No operations match these filters'}
 return <main className="page-content operational-register"><header className="page-heading"><div><span className="eyebrow"><Waypoints size={15}/>{labels.k}</span><h1>{labels.title}</h1><p>{labels.desc}</p></div><button className="primary-button" onClick={exportCsv}><Download size={17}/>{labels.export}</button></header><section className="operational-toolbar"><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={labels.search}/></label><label><Filter size={17}/><select value={category} onChange={e=>setCategory(e.target.value as typeof category)}><option value="all">{labels.all}</option>{['intake','production','movement','supply','ageing','bottling'].map(x=><option key={x} value={x}>{x}</option>)}</select></label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></section><section className="operational-list">{filtered.map(e=><article key={e.id} className={`operational-row ${e.status==='reversed'?'reversed':''}`}><span className={`operational-kind ${e.category}`}>{e.category}</span><div><strong>{e.title}</strong><small>{formatZonedDateTime(e.performedAt, locale, timeZone)} · {formatRelativeTime(e.performedAt, locale, now)} · {e.operator}</small><em>{[e.source&&`↗ ${e.source}`,e.destination&&`↘ ${e.destination}`,e.quantity!==undefined&&`${e.quantity} ${e.unit||''}`].filter(Boolean).join(' · ')}</em></div><span className="operational-ref">{e.reference}</span></article>)}{!filtered.length&&<div className="operational-empty">{labels.empty}</div>}</section></main>
}
