import type { BarrelOperation, BottlingOrder, GrapeDelivery, ProductStockTransaction, ProductionEvent, WeatherSnapshot, WineLot, WineMovement } from './types'

export type OperationalEventCategory = 'intake' | 'production' | 'movement' | 'supply' | 'ageing' | 'bottling'
export interface OperationalEvent {
  id: string; category: OperationalEventCategory; type: string; title: string; performedAt: string; recordedAt: string; operator: string
  quantity?: number; unit?: string; source?: string; destination?: string; wineLotId?: string; productLotId?: string; reference?: string; status?: 'active'|'reversed'; notes: string; weather?: WeatherSnapshot
}
export interface OperationalSources { lots: WineLot[]; deliveries: GrapeDelivery[]; productionEvents: ProductionEvent[]; movements: WineMovement[]; productTransactions: ProductStockTransaction[]; barrelOperations: BarrelOperation[]; bottlingOrders: BottlingOrder[]; weatherSnapshots?: WeatherSnapshot[] }
const iso = (value?: string) => value || new Date(0).toISOString()
export function buildOperationalRegister(s: OperationalSources): OperationalEvent[] {
  const lotNames = new Map(s.lots.map(l => [l.id, l.name]))
  const result: OperationalEvent[] = []
  const weatherByEntity = new Map((s.weatherSnapshots ?? []).map(snapshot => [`${snapshot.entityType}:${snapshot.entityId}`, snapshot]))
  s.deliveries.filter(d => d.receivedAt).forEach(d => result.push({ id:`intake:${d.id}`, category:'intake', type:'grape_receipt', title:`Recepción ${d.code}`, performedAt:iso(d.receivedAt), recordedAt:iso(d.receivedAt), operator:d.grower, quantity:d.netKg, unit:'kg', source:d.origin, destination:d.processingDestination, reference:d.id, notes:d.notes || '', weather: weatherByEntity.get(`grape_delivery:${d.id}`) }))
  s.productionEvents.forEach(e => result.push({ id:`production:${e.id}`, category:'production', type:e.kind === 'transition' ? 'stage_transition' : String(e.operationType || 'operation'), title:e.kind === 'transition' ? `${lotNames.get(e.lotId)||e.lotId}: ${e.fromStageId} → ${e.toStageId}` : `${lotNames.get(e.lotId)||e.lotId}: ${e.operationType || 'Operación'}`, performedAt:e.performedAt, recordedAt:e.recordedAt, operator:e.operator, wineLotId:e.lotId, reference:e.id, notes:e.notes, weather: weatherByEntity.get(`production_event:${e.id}`) }))
  s.movements.forEach(m => result.push({ id:`movement:${m.id}`, category:'movement', type:m.kind, title:`${m.code} · ${m.kind}`, performedAt:m.performedAt, recordedAt:m.recordedAt, operator:m.operator, quantity:m.receivedVolume, unit:'L', source:m.sourceLegs.map(x=>x.vesselId).join(', '), destination:m.destinationLegs.map(x=>x.vesselId).join(', '), wineLotId:m.destinationLegs[0]?.lotId || m.sourceLegs[0]?.lotId, reference:m.id, notes:m.notes, weather: weatherByEntity.get(`wine_movement:${m.id}`) }))
  s.productTransactions.forEach(t => result.push({ id:`supply:${t.id}`, category:'supply', type:t.type, title:`${t.type.replaceAll('_',' ')} · ${t.productLotId}`, performedAt:t.occurredAt, recordedAt:t.recordedAt, operator:t.operator, quantity:t.quantity, unit:t.unit, source:t.fromLocation, destination:t.toLocation, wineLotId:t.wineLotId, productLotId:t.productLotId, reference:t.reference || t.id, status:t.status, notes:t.notes || t.reason || '' }))
  s.barrelOperations.forEach(o => result.push({ id:`ageing:${o.id}`, category:'ageing', type:o.type, title:`${o.type.replaceAll('_',' ')} · ${o.targetLabel}`, performedAt:o.performedAt, recordedAt:o.performedAt, operator:o.person, quantity:o.volumeAdded, unit:o.volumeAdded ? 'L' : undefined, destination:o.targetLabel, reference:o.id, notes:o.notes }))
  s.bottlingOrders.forEach(o => { result.push({ id:`bottling:${o.id}:created`, category:'bottling', type:'order_created', title:`${o.code} · ${o.wineName}`, performedAt:o.createdAt, recordedAt:o.createdAt, operator:o.createdBy, quantity:o.targetVolume, unit:'L', reference:o.id, notes:'', weather: weatherByEntity.get(`bottling_order:${o.id}`) }); if(o.completion) result.push({ id:`bottling:${o.id}:completed`, category:'bottling', type:'bottling_completed', title:`${o.code} · ${o.completion.finishedProductLot}`, performedAt:o.completion.completedAt, recordedAt:o.completion.completedAt, operator:o.completion.completedBy, quantity:o.completion.actualVolume, unit:'L', reference:o.id, notes:o.completion.notes, weather: weatherByEntity.get(`bottling_order:${o.id}`) }) })
  return result.sort((a,b)=>Date.parse(b.performedAt)-Date.parse(a.performedAt))
}
export function operationalRegisterCsv(events: OperationalEvent[]) { const q=(v:unknown)=>`"${String(v??'').replaceAll('"','""')}"`; return ['ID,Categoría,Tipo,Título,Realizado,Registrado,Operador,Cantidad,Unidad,Origen,Destino,Lote de vino,Lote de producto,Referencia,Estado,Temperatura °C,Humedad %,Viento km/h,Precipitación mm,Estado meteo,Fuente meteo,Notas', ...events.map(e=>[e.id,e.category,e.type,e.title,e.performedAt,e.recordedAt,e.operator,e.quantity,e.unit,e.source,e.destination,e.wineLotId,e.productLotId,e.reference,e.status||'active',e.weather?.temperatureC,e.weather?.relativeHumidity,e.weather?.windSpeedKmh,e.weather?.precipitationMm,e.weather?.status,e.weather?.source,e.notes].map(q).join(','))].join('\n') }
