import { useMemo, useState, type FormEvent, type ReactNode } from 'react'
import {
  ArrowLeft, ArrowRight, ArrowUpRight, Boxes, CheckCircle2, ChevronRight, CircleAlert,
  ClipboardCheck, Clock3, FileCheck2, FlaskConical, Grape, Package, Plus, RotateCcw,
  ScanLine, Search, ShieldCheck, TestTube2, Truck, Warehouse, Waypoints, Wine, X,
} from 'lucide-react'
import { images } from './data'
import { traceEntityScope } from './domain'
import { useLanguage } from './i18n'
import type {
  NewRecallSimulationInput, RecallReason, RecallSimulation, TraceabilityDirection,
  TraceabilityEntity, TraceabilityEntityStatus, TraceabilityEntityType, TraceabilityLink, TraceabilityRelation,
} from './types'

const typeKeys: Record<TraceabilityEntityType, 'trace.typeParcel' | 'trace.typeDelivery' | 'trace.typeWineLot' | 'trace.typeBarrels' | 'trace.typeBlend' | 'trace.typeBottling' | 'trace.typeFinished' | 'trace.typePackaging'> = {
  parcel: 'trace.typeParcel', grape_delivery: 'trace.typeDelivery', wine_lot: 'trace.typeWineLot', barrel_group: 'trace.typeBarrels', blend: 'trace.typeBlend', bottling_order: 'trace.typeBottling', finished_lot: 'trace.typeFinished', packaging_lot: 'trace.typePackaging',
}
const statusKeys: Record<TraceabilityEntityStatus, 'trace.statusVerified' | 'trace.statusPending' | 'trace.statusAttention'> = { verified: 'trace.statusVerified', pending: 'trace.statusPending', attention: 'trace.statusAttention' }
const relationKeys: Record<TraceabilityRelation, 'trace.relationHarvested' | 'trace.relationProcessed' | 'trace.relationAged' | 'trace.relationComponent' | 'trace.relationBottled' | 'trace.relationProduced' | 'trace.relationPackaged'> = {
  harvested_into: 'trace.relationHarvested', processed_as: 'trace.relationProcessed', aged_in: 'trace.relationAged', component_of: 'trace.relationComponent', bottled_as: 'trace.relationBottled', produced_as: 'trace.relationProduced', packaged_with: 'trace.relationPackaged',
}
const reasonKeys: Record<RecallReason, 'trace.reasonQuality' | 'trace.reasonPackaging' | 'trace.reasonLabelling' | 'trace.reasonTest'> = { quality: 'trace.reasonQuality', packaging: 'trace.reasonPackaging', labelling: 'trace.reasonLabelling', trace_test: 'trace.reasonTest' }
const stageTypes: { key: 'origin' | 'wine' | 'blend' | 'bottle'; types: TraceabilityEntityType[] }[] = [
  { key: 'origin', types: ['parcel', 'grape_delivery'] }, { key: 'wine', types: ['wine_lot', 'barrel_group'] }, { key: 'blend', types: ['blend'] }, { key: 'bottle', types: ['bottling_order', 'finished_lot', 'packaging_lot'] },
]
const formatQuantity = (entity: TraceabilityEntity, locale: string) => entity.quantity === undefined ? '—' : `${new Intl.NumberFormat(locale).format(entity.quantity)} ${entity.unit ?? ''}`

function EntityIcon({ type }: { type: TraceabilityEntityType }) {
  const icons: Record<TraceabilityEntityType, ReactNode> = { parcel: <Grape />, grape_delivery: <Truck />, wine_lot: <Wine />, barrel_group: <Warehouse />, blend: <FlaskConical />, bottling_order: <Package />, finished_lot: <ScanLine />, packaging_lot: <Boxes /> }
  return icons[type]
}

interface TraceabilityPageProps {
  entities: TraceabilityEntity[]
  links: TraceabilityLink[]
  simulations: RecallSimulation[]
  onCreateSimulation: (input: NewRecallSimulationInput) => void
}

export function TraceabilityPage({ entities, links, simulations, onCreateSimulation }: TraceabilityPageProps) {
  const [view, setView] = useState<'explorer' | 'registry' | 'recall'>('explorer')
  const [selectedId, setSelectedId] = useState(() => entities.find((entity) => entity.type === 'finished_lot')?.id ?? entities[0]?.id ?? '')
  const [drawerId, setDrawerId] = useState<string | null>(null)
  const [direction, setDirection] = useState<TraceabilityDirection>('backward')
  const [query, setQuery] = useState('')
  const [typeFilter, setTypeFilter] = useState<'all' | TraceabilityEntityType>('all')
  const [recallOpen, setRecallOpen] = useState(false)
  const { t, locale } = useLanguage()
  const selected = entities.find((entity) => entity.id === selectedId) ?? entities[0]
  const drawerEntity = entities.find((entity) => entity.id === drawerId)
  const scope = useMemo(() => selected ? traceEntityScope(selected.id, entities, links, direction) : [], [selected, entities, links, direction])
  const visibleIds = new Set(scope.map((entity) => entity.id))
  const visibleLinks = links.filter((link) => visibleIds.has(link.sourceId) && visibleIds.has(link.targetId))
  const verifiedLinks = links.filter((link) => link.status === 'verified').length
  const completeness = links.length ? Math.round(verifiedLinks / links.length * 100) : 100
  const finishedLots = entities.filter((entity) => entity.type === 'finished_lot')
  const attention = entities.filter((entity) => entity.status !== 'verified').length + links.filter((link) => link.status !== 'verified').length
  const normalized = query.trim().toLowerCase()
  const results = entities.filter((entity) => (typeFilter === 'all' || entity.type === typeFilter) && (!normalized || [entity.code, entity.name, entity.subtitle, ...Object.values(entity.metadata)].some((value) => value.toLowerCase().includes(normalized))))

  const chooseEntity = (id: string) => { setSelectedId(id); setDrawerId(null); setView('explorer') }
  return <main className="trace-page">
    <header className="page-header"><div><span className="eyebrow">{t('trace.kicker')}</span><h1>{t('trace.title')}</h1><p>{t('trace.description')}</p></div><div className="page-header-action"><button className="primary-button" onClick={() => setRecallOpen(true)}><RotateCcw size={17} /> {t('trace.newSimulation')}</button></div></header>

    <section className="trace-hero" style={{ backgroundImage: `url(${images.vineyard})` }}><div className="trace-hero-overlay" /><div className="trace-hero-copy"><span className="trace-season"><Waypoints size={15} /> {t('trace.completeGenealogy')}</span><h2>{t('trace.heroTitle')}</h2><p>{t('trace.heroText')}</p><div className="trace-hero-badges"><span><ShieldCheck size={15} /> {t('trace.verifiedEvidence')}</span><span><ArrowLeft size={15} /><ArrowRight size={15} /> {t('trace.twoDirections')}</span></div></div><div className="trace-focus-card"><span className={`trace-focus-icon ${selected?.type}`}><EntityIcon type={selected?.type ?? 'finished_lot'} /></span><div><small>{t('trace.currentFocus')}</small><strong>{selected?.name}</strong><span>{selected?.code} · {selected ? t(typeKeys[selected.type]) : ''}</span></div><em>{scope.length} {t('trace.connected').toLowerCase()}</em></div></section>

    <section className="trace-metrics" aria-label={t('trace.summary')}><TraceMetric icon={<ScanLine />} label={t('trace.finishedLots')} value={String(finishedLots.length)} detail={t('trace.searchableByBottle')} tone="wine" /><TraceMetric icon={<Waypoints />} label={t('trace.verifiedLinks')} value={`${verifiedLinks}/${links.length}`} detail={t('trace.withEvidence')} tone="blue" /><TraceMetric icon={<CheckCircle2 />} label={t('trace.completeness')} value={`${completeness}%`} detail={t('trace.internalCoverage')} tone="success" /><TraceMetric icon={<CircleAlert />} label={t('trace.attentionItems')} value={String(attention)} detail={t('trace.pendingReview')} tone="gold" /></section>

    <div className="trace-toolbar"><div className="harvest-tabs trace-tabs" role="tablist">{(['explorer', 'registry', 'recall'] as const).map((item) => <button key={item} role="tab" aria-selected={view === item} className={view === item ? 'active' : ''} onClick={() => setView(item)}>{t(item === 'explorer' ? 'trace.explorer' : item === 'registry' ? 'trace.registry' : 'trace.simulations')}</button>)}</div><label className="trace-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('trace.searchPlaceholder')} /></label></div>

    {view === 'explorer' && selected && <>
      <section className="trace-focus-strip"><button onClick={() => setDrawerId(selected.id)}><span className={`trace-node-icon ${selected.type}`}><EntityIcon type={selected.type} /></span><span><small>{t('trace.tracingFrom')}</small><strong>{selected.code} · {selected.name}</strong></span><ArrowUpRight size={16} /></button><div className="direction-switch">{(['backward', 'both', 'forward'] as const).map((item) => <button key={item} className={direction === item ? 'active' : ''} onClick={() => setDirection(item)}>{item === 'backward' ? <ArrowLeft /> : item === 'forward' ? <ArrowRight /> : <Waypoints />}{t(item === 'backward' ? 'trace.backward' : item === 'forward' ? 'trace.forward' : 'trace.both')}</button>)}</div></section>
      <section className="genealogy-shell"><header><div><span className="eyebrow">{t('trace.visualMap')}</span><h2>{t('trace.genealogy')}</h2><p>{t('trace.genealogyText')}</p></div><span className="genealogy-scope"><strong>{scope.length}</strong><small>{t('trace.connectedRecords')}</small></span></header><div className="genealogy-board">{stageTypes.map((stage, stageIndex) => { const stageEntities = scope.filter((entity) => stage.types.includes(entity.type)); return <section className={`genealogy-stage stage-${stage.key}`} key={stage.key}><header><span>{stageIndex + 1}</span><div><strong>{t(`trace.stage${stage.key[0].toUpperCase()}${stage.key.slice(1)}` as 'trace.stageOrigin')}</strong><small>{stageEntities.length} {t('trace.records').toLowerCase()}</small></div></header><div>{stageEntities.map((entity) => <TraceNode key={entity.id} entity={entity} active={entity.id === selected.id} onClick={() => setDrawerId(entity.id)} />)}{!stageEntities.length && <span className="empty-stage">{t('trace.noRecordsDirection')}</span>}</div>{stageIndex < stageTypes.length - 1 && <span className="stage-connector"><ChevronRight /></span>}</section> })}</div><div className="trace-link-evidence"><header><strong>{t('trace.evidenceTrail')}</strong><small>{visibleLinks.length} {t('trace.linksInView')}</small></header><div>{visibleLinks.slice(0, 8).map((link) => <button key={link.id} onClick={() => setDrawerId(link.targetId)}><span className={`link-status ${link.status}`}><FileCheck2 /></span><span><strong>{t(relationKeys[link.relation])}</strong><small>{link.evidence}</small></span><em>{link.quantity ? `${new Intl.NumberFormat(locale).format(link.quantity)} ${link.unit}` : '—'}</em></button>)}</div></div></section>
    </>}

    {view === 'registry' && <section className="trace-registry"><div className="trace-registry-head"><div><h2>{t('trace.registryTitle')}</h2><p>{t('trace.registryText')}</p></div><div className="filter-chips trace-type-filters">{([['all', t('trace.all')], ['finished_lot', t('trace.finished')], ['wine_lot', t('trace.wineLots')], ['parcel', t('trace.parcels')], ['packaging_lot', t('trace.packaging')]] as const).map(([value, label]) => <button key={value} className={typeFilter === value ? 'active' : ''} onClick={() => setTypeFilter(value)}>{label}</button>)}</div></div><div className="trace-registry-grid">{results.map((entity) => <RegistryCard key={entity.id} entity={entity} onOpen={() => setDrawerId(entity.id)} onTrace={() => chooseEntity(entity.id)} />)}</div>{!results.length && <div className="trace-empty"><Search /><strong>{t('trace.noResults')}</strong><span>{t('trace.noResultsText')}</span></div>}</section>}

    {view === 'recall' && <section className="recall-page-section"><div className="recall-section-head"><div><h2>{t('trace.simulationHistory')}</h2><p>{t('trace.simulationHistoryText')}</p></div><button className="secondary-button" onClick={() => setRecallOpen(true)}><Plus size={16} /> {t('trace.newSimulation')}</button></div><div className="recall-grid">{simulations.map((simulation) => <RecallCard key={simulation.id} simulation={simulation} entities={entities} onTrace={chooseEntity} />)}</div></section>}

    {drawerEntity && <EntityDrawer entity={drawerEntity} entities={entities} links={links} onClose={() => setDrawerId(null)} onTrace={() => chooseEntity(drawerEntity.id)} />}
    {recallOpen && <RecallSimulationSheet entities={entities} links={links} onClose={() => setRecallOpen(false)} onCreate={(input) => { onCreateSimulation(input); setRecallOpen(false); setView('recall') }} />}
  </main>
}

function TraceMetric({ icon, label, value, detail, tone }: { icon: ReactNode; label: string; value: string; detail: string; tone: string }) { return <article className="trace-metric"><span className={`trace-metric-icon ${tone}`}>{icon}</span><span><small>{label}</small><strong>{value}</strong><em>{detail}</em></span></article> }
function TraceNode({ entity, active, onClick }: { entity: TraceabilityEntity; active: boolean; onClick: () => void }) { const { t, locale } = useLanguage(); return <button className={`trace-node ${entity.type} ${entity.status} ${active ? 'active' : ''}`} onClick={onClick}><span className="trace-node-icon"><EntityIcon type={entity.type} /></span><span><small>{t(typeKeys[entity.type])}</small><strong>{entity.code}</strong><em>{entity.name}</em><i>{formatQuantity(entity, locale)}</i></span><span className={`trace-status-dot ${entity.status}`} title={t(statusKeys[entity.status])} /></button> }

function RegistryCard({ entity, onOpen, onTrace }: { entity: TraceabilityEntity; onOpen: () => void; onTrace: () => void }) {
  const { t, locale } = useLanguage(); return <article className={`trace-registry-card ${entity.type}`}><div className="registry-card-visual" style={entity.image ? { backgroundImage: `url(${entity.image})` } : undefined}><span className="registry-card-overlay" /><span className="registry-type"><EntityIcon type={entity.type} /> {t(typeKeys[entity.type])}</span><span className={`trace-entity-status ${entity.status}`}>{t(statusKeys[entity.status])}</span></div><div className="registry-card-body"><span className="eyebrow">{entity.code}</span><h3>{entity.name}</h3><p>{entity.subtitle}</p><div className="registry-card-meta"><span><small>{t('trace.quantity')}</small><strong>{formatQuantity(entity, locale)}</strong></span><span><small>{t('trace.date')}</small><strong>{new Intl.DateTimeFormat(locale, { day: '2-digit', month: 'short', year: '2-digit' }).format(new Date(entity.occurredAt))}</strong></span></div><div><button className="secondary-button" onClick={onOpen}>{t('common.view')}</button><button className="text-button" onClick={onTrace}><Waypoints size={15} /> {t('trace.trace')}</button></div></div></article>
}

function EntityDrawer({ entity, entities, links, onClose, onTrace }: { entity: TraceabilityEntity; entities: TraceabilityEntity[]; links: TraceabilityLink[]; onClose: () => void; onTrace: () => void }) {
  const { t, d, locale } = useLanguage(); const incoming = links.filter((link) => link.targetId === entity.id); const outgoing = links.filter((link) => link.sourceId === entity.id); const related = (id: string) => entities.find((item) => item.id === id)
  return <div className="sheet-layer"><button className="sheet-scrim" onClick={onClose} aria-label={t('common.close')} /><aside className="trace-drawer"><header className="drawer-head"><div><span className="eyebrow">{entity.code}</span><h2>{entity.name}</h2><p>{entity.subtitle}</p></div><button className="icon-button" onClick={onClose}><X size={20} /></button></header><div className={`trace-drawer-hero ${entity.type}`}><span className="trace-drawer-icon"><EntityIcon type={entity.type} /></span><div><span className={`trace-entity-status ${entity.status}`}>{t(statusKeys[entity.status])}</span><strong>{t(typeKeys[entity.type])}</strong><small>{formatQuantity(entity, locale)} · {new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(entity.occurredAt))}</small></div></div><section className="trace-drawer-section"><h3>{t('trace.recordData')}</h3><div className="trace-metadata-grid">{Object.entries(entity.metadata).map(([key, value]) => <span key={key}><small>{d(key.replaceAll('_', ' '))}</small><strong>{d(value)}</strong></span>)}</div></section><section className="trace-drawer-section"><h3>{t('trace.incomingEvidence')}</h3><LinkList links={incoming} direction="incoming" related={related} /></section><section className="trace-drawer-section"><h3>{t('trace.outgoingEvidence')}</h3><LinkList links={outgoing} direction="outgoing" related={related} /></section><div className="trace-drawer-actions"><button className="primary-button" onClick={onTrace}><Waypoints size={16} /> {t('trace.openInExplorer')}</button></div></aside></div>
}

function LinkList({ links, direction, related }: { links: TraceabilityLink[]; direction: 'incoming' | 'outgoing'; related: (id: string) => TraceabilityEntity | undefined }) {
  const { t, locale } = useLanguage(); if (!links.length) return <span className="trace-no-links">{t('trace.noLinks')}</span>; return <div className="drawer-link-list">{links.map((link) => { const entity = related(direction === 'incoming' ? link.sourceId : link.targetId); return <article key={link.id}><span className={`link-status ${link.status}`}><FileCheck2 /></span><span><strong>{entity?.code} · {entity?.name}</strong><small>{t(relationKeys[link.relation])} · {link.evidence}</small></span><em>{link.quantity ? `${new Intl.NumberFormat(locale).format(link.quantity)} ${link.unit}` : '—'}</em></article> })}</div>
}

function RecallCard({ simulation, entities, onTrace }: { simulation: RecallSimulation; entities: TraceabilityEntity[]; onTrace: (id: string) => void }) {
  const { t, d, locale } = useLanguage(); const target = entities.find((entity) => entity.id === simulation.targetEntityId)
  return <article className="recall-card"><header><span className="recall-icon"><TestTube2 /></span><span><small>{simulation.code}</small><strong>{t(reasonKeys[simulation.reason])}</strong></span><em><CheckCircle2 /> {t('trace.completed')}</em></header><div className="recall-target"><span className={`trace-node-icon ${target?.type}`}><EntityIcon type={target?.type ?? 'finished_lot'} /></span><span><small>{t('trace.simulationTarget')}</small><strong>{simulation.targetCode} · {target?.name}</strong></span></div><p>{d(simulation.notes)}</p><div className="recall-impact-grid"><span><small>{t('trace.affectedRecords')}</small><strong>{simulation.affectedEntityIds.length}</strong></span><span><small>{t('trace.affectedFinished')}</small><strong>{simulation.affectedFinishedLotIds.length}</strong></span><span><small>{t('trace.affectedOrders')}</small><strong>{simulation.affectedBottlingOrderIds.length}</strong></span><span><small>{t('trace.sourceParcels')}</small><strong>{simulation.sourceParcelIds.length}</strong></span></div><footer><span><Clock3 size={14} /> {new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(simulation.createdAt))} · {simulation.createdBy}</span><button className="text-button" onClick={() => onTrace(simulation.targetEntityId)}>{t('trace.openScope')} <ArrowUpRight size={14} /></button></footer></article>
}

function RecallSimulationSheet({ entities, links, onClose, onCreate }: { entities: TraceabilityEntity[]; links: TraceabilityLink[]; onClose: () => void; onCreate: (input: NewRecallSimulationInput) => void }) {
  const candidates = entities.filter((entity) => ['finished_lot', 'packaging_lot', 'wine_lot', 'parcel'].includes(entity.type)); const [draft, setDraft] = useState<NewRecallSimulationInput>({ targetEntityId: candidates[0]?.id ?? '', reason: 'trace_test', notes: '' }); const [error, setError] = useState(''); const { t } = useLanguage(); const target = entities.find((entity) => entity.id === draft.targetEntityId); const scope = target ? traceEntityScope(target.id, entities, links, 'both') : []; const finished = scope.filter((entity) => entity.type === 'finished_lot').length; const orders = scope.filter((entity) => entity.type === 'bottling_order').length; const parcels = scope.filter((entity) => entity.type === 'parcel').length
  const submit = (event: FormEvent) => { event.preventDefault(); if (!draft.targetEntityId || !draft.notes.trim()) return setError(t('trace.errorSimulation')); onCreate(draft) }
  return <div className="sheet-layer lot-flow-layer"><button className="sheet-scrim" onClick={onClose} /><form className="lot-flow recall-flow" onSubmit={submit}><header className="lot-flow-head"><div><span className="flow-type-icon recall"><RotateCcw /></span><span><small>{t('trace.workspace')}</small><strong>{t('trace.newSimulation')}</strong></span></div><button type="button" className="icon-button" onClick={onClose}><X size={20} /></button></header><div className="lot-flow-body"><section className="flow-section"><div className="flow-title"><span className="eyebrow">{t('trace.impactAnalysis')}</span><h2>{t('trace.testTraceability')}</h2><p>{t('trace.testTraceabilityText')}</p></div><div className="form-grid"><TraceField label={t('trace.targetRecord')} wide><select value={draft.targetEntityId} onChange={(event) => setDraft({ ...draft, targetEntityId: event.target.value })}>{candidates.map((entity) => <option key={entity.id} value={entity.id}>{entity.code} · {entity.name}</option>)}</select></TraceField><TraceField label={t('trace.reason')} wide><select value={draft.reason} onChange={(event) => setDraft({ ...draft, reason: event.target.value as RecallReason })}>{(Object.keys(reasonKeys) as RecallReason[]).map((reason) => <option key={reason} value={reason}>{t(reasonKeys[reason])}</option>)}</select></TraceField><TraceField label={t('trace.simulationNotes')} wide><textarea value={draft.notes} onChange={(event) => setDraft({ ...draft, notes: event.target.value })} placeholder={t('trace.simulationNotesPlaceholder')} /></TraceField></div><div className="recall-scope-preview"><header><Waypoints /><span><strong>{t('trace.calculatedScope')}</strong><small>{t('trace.calculatedScopeText')}</small></span></header><div><span><small>{t('trace.affectedRecords')}</small><strong>{scope.length}</strong></span><span><small>{t('trace.affectedFinished')}</small><strong>{finished}</strong></span><span><small>{t('trace.affectedOrders')}</small><strong>{orders}</strong></span><span><small>{t('trace.sourceParcels')}</small><strong>{parcels}</strong></span></div></div><div className="trace-simulation-note"><ClipboardCheck /><span><strong>{t('trace.simulationOnly')}</strong><small>{t('trace.simulationOnlyText')}</small></span></div>{error && <div className="form-error">{error}</div>}</section></div><footer className="lot-flow-actions"><button type="button" className="secondary-button" onClick={onClose}>{t('common.cancel')}</button><button className="primary-button"><TestTube2 size={16} /> {t('trace.runSimulation')}</button></footer></form></div>
}

function TraceField({ label, wide = false, children }: { label: string; wide?: boolean; children: ReactNode }) { return <label className={`flow-field trace-field ${wide ? 'wide' : ''}`}><span>{label}</span><div>{children}</div></label> }
